AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Read aws analytics service questions from stackoverflow and push to
  ElasticSearch cluster and S3 bucket once every day'
Globals:
  Function:
    Timeout: 120
    Tags:
      auto-delete: false
      project: personal
Resources:
  StackOverFlowApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StackOverFlowApiFunction
      Description: Read aws analytics service questions from stackoverflow and push
        to ElasticSearch cluster
      Handler: main.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Environment:
        Variables:
          tags : aws-elasticsearch,amazon-kinesis,amazon-kinesis-firehose,amazon-kinesis-analytics,amazon-elasticsearch,aws-msk
          index : stackoverflow-index
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          - s3:Get*
          Resource:
          - arn:aws:s3:::stackoverflow-questions-bucket
          - arn:aws:s3:::stackoverflow-questions-bucket/*
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: 
          - !GetAtt DestinationSearchFunction.Arn
        - Effect: Allow
          Action:
          - ssm:GetParameters
          Resource:
          - arn:aws:ssm:us-east-1:649687724644:parameter/project-stackoverflow*
      Events:
        DailyEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: DailyScheduleForStackOverFlow
            Description: Invoke lambda function daily once
            Enabled: true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: Lambda
            Destination: !GetAtt DestinationSearchFunction.Arn
    DependsOn: 
    - DestinationSearchFunction     
  DestinationSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DestinationSearchFunction
      Description: Perform search request against ES and forward result to chime webhook
      Handler: search-query.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Environment:
        Variables:
          index : stackoverflow-index
          source : tag,title,link,is_answered,creation_date
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ssm:GetParameters
          Resource:
          - arn:aws:ssm:us-east-1:649687724644:parameter/project-stackoverflow*
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: Lambda
            Destination: !GetAtt RedshiftLoadFunction.Arn
    DependsOn: 
    - RedshiftLoadFunction
  RedshiftLoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RedshiftLoadFunction
      Description: Load data to redshift from s3 bucket
      Handler: redshift-load.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Environment:
        Variables:
          clustername : redshift-test-cluster
          rshost : redshift-test-cluster.ch6emrqxfmh2.us-east-1.redshift.amazonaws.com
          db : dev
          user : lambda_user
          usergroup : stack_group
          bucket : stackoverflow-questions-bucket
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - redshift:GetClusterCredentials
          - redshift:CreateClusterUser
          - redshift:JoinGroup
          Resource:
          - arn:aws:redshift:us-east-1:649687724644:dbuser:redshift-test-cluster/lambda_user
          - arn:aws:redshift:us-east-1:649687724644:dbname:redshift-test-cluster/dev
          - arn:aws:redshift:us-east-1:649687724644:dbgroup:redshift-test-cluster/stack_group
        - Effect: Allow
          Action:
          - s3:List*
          Resource:
          - arn:aws:s3:::stackoverflow-questions-bucket
          - arn:aws:s3:::stackoverflow-questions-bucket/*
Outputs:
  LambdaFunctionIamRole:
    Description: Implicit IAM Role created for lambda function
    Value:
      Fn::GetAtt:
      - StackOverFlowApiFunctionRole
      - Arn
